name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: install dependencies
      run: |
        sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: make
      run: make
