name: OSX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: qmake
      run: qmake interface/Interface.pro
    - name: make
      run: make
